# Generated by Django 3.1.3 on 2020-11-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_todo_app', '0002_auto_20201129_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
