# Generated by Django 3.1.3 on 2020-11-30 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_todo_app', '0005_auto_20201130_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='name',
            new_name='text',
        ),
        migrations.AddField(
            model_name='tasks',
            name='completed_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
